name: Main

on:
  workflow_dispatch:
     inputs:
      publish:
        description: Publish to nuget
        type: boolean
        required: false
        default: false

env:
  DOTNET_NOLOGO: 1

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build Debug
        run: dotnet build -c Debug --no-restore

      - name: Build Release
        run: dotnet build -c Release --no-restore

      - name: Test Debug
        run: dotnet test -c Debug --no-build

      - name: Test Release
        run: dotnet test -c Release --no-build

      - name: Pack
        run: dotnet pack -c Release --no-build -o output

      - name: Upload NuGet
        if: ${{ inputs.publish }}
        run: dotnet nuget push output\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}